export default {
  //declare colors here
  themePrimary: '#ED03BF',
  disabledButton: '#FF9FEC',
  white: '#FFFFFF',
  black: '#000000',
  primaryFont: '#000',
  secondaryFont: '#474747',
  borderColor: '#E6E6E6',
  dropDownSelected: '#A1A1A1',
  textBackGround: '#F1F1F1',
  darkTextBg: '#595959',
  levelCardBackGround: '#171717',
  favItemCardBackGround: '#DDDDDD',
  selectedOptionBackground: '#FFC1F3',
  placeHolderFontColor: '#6B6B6B',
  rankStandingBgColor: '#F974DF',
  disabledText: '#A1A1A1',
  correctAnswerBackground: '#C7FFC1',
  incorrectAnsBackGround: '#FFC1C2',
};
